// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

/** Prisma CLI (migrate, studio) needs a direct DB connection — pooled Neon URLs cause P1002. */
function getMigrationUrl(): string {
  if (process.env["DIRECT_URL"]) {
    return process.env["DIRECT_URL"];
  }

  const databaseUrl = process.env["DATABASE_URL"];
  if (!databaseUrl) {
    return env("DATABASE_URL");
  }

  // Neon pooled hostnames include "-pooler"; strip it for migrations.
  if (databaseUrl.includes("-pooler.")) {
    return databaseUrl.replace("-pooler.", ".");
  }

  return databaseUrl;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getMigrationUrl(),
  },
});
